services:
  - type: web
    name: worktable-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot/bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "6706048508:AAF-8InmBKwP1x7DA-ET8D282c5pp0Rn2Y"
      - key: TELEGRAM_GROUP_ID
        value: "-1002583331823"
      - key: SUPABASE_URL
        value: "https://xpwewmibfiekbigxc.supabase.co"
      - key: SUPABASE_KEY
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhwd2V3bWliZmlla2JnaXhjeCIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjQ0NzI2NzIwLCJleHAiOjE5NTk4MDY3MjB9.5hmyLzEIpWUE9w2rVJ_kA_S1_HLQs7"
